/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package id.go.bps.sambas.kalbar.sutp2016.form;

import id.go.bps.sambas.kalbar.sutp2016.MainFrame;
import id.go.bps.sambas.kalbar.sutp2016.functions.DSBSService;
import id.go.bps.sambas.kalbar.sutp2016.resources.ResourceLoader;
import id.go.bps.sambas.kalbar.sutp2016.resources.Strings;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author dekteguh
 */
public class FormBackupRestore extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private String username;
    private JFileChooser jfc;

    /**
     * Creates new form PesertaForm
     */
    public FormBackupRestore(MainFrame frame, String userName) {
        this.mainFrame = frame;
        this.username = userName;
        initComponents();
        this.cmdProvinsi.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String idx = loadKode(cmdProvinsi.getSelectedItem().toString());
                loadKabupaten(idx);
            }
        });
    }

    public void showDialog(String util) {
        jfc = new JFileChooser();
        jfc.setApproveButtonText(util);
        jfc.setFileFilter(new FileNameExtensionFilter("Import DSBS", "xls"));
        jfc.setDialogTitle(util);
        jfc.setApproveButtonToolTipText(util + " data");
    }

    private String loadKode(String kode) {
        String code;
        String[] pecah = kode.split(" - ");
        code = pecah[0];
        return code;
    }

    private void loadKabupaten(String kode) {
        cmbKako.setSelectedIndex(1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                g.drawImage(new ImageIcon(ResourceLoader.getResource(Strings.BACKGROUND_)).getImage(),0,0,null);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        buttonBackupData = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbTahun = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbSubround = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmdProvinsi = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cmbKako = new javax.swing.JComboBox();
        buttonRestoreData = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(980, 500));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BACKUP DAN RESTORE DATA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonBackupData.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        buttonBackupData.setText("Backup Data");
        buttonBackupData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackupDataActionPerformed(evt);
            }
        });

        jLabel2.setText("Pilih Tahun:");

        cmbTahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih Tahun-", "2016", "2017", "2018", "2019", "2020" }));

        jLabel3.setText("Pilih Subround:");

        cmbSubround.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih Subround-", "1", "2", "3" }));

        jLabel4.setText("Pilih Provinsi:");

        cmdProvinsi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih Provinsi-", "61 - Kalimantan Barat" }));

        jLabel5.setText("Pilih Kabupaten:");

        cmbKako.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Kabupaten/Kota-", "01 - Sambas" }));

        buttonRestoreData.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        buttonRestoreData.setText("Restore Data");
        buttonRestoreData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRestoreDataActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 956, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cmbSubround, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 232, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cmbTahun, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 232, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cmdProvinsi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 232, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(buttonBackupData)
                                    .add(cmbKako, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 232, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(buttonRestoreData))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(cmbTahun, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(cmbSubround, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(cmdProvinsi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(cmbKako, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(buttonBackupData)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(buttonRestoreData)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackupDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackupDataActionPerformed
        // TODO add your handling code here:
        String nama = null;
        showDialog("Import");
        if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            try {
                nama = jfc.getSelectedFile().getAbsolutePath();
                if (!nama.contains(".xls")) {
                    nama = nama + ".xls";
                }
                long result = DSBSService.importDSBS(nama);
                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "Data berhasil diimport.", "Info", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Data gagal diimport.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                Logger.getLogger(FormBackupRestore.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            return;
        }

        //JOptionPane.showMessageDialog(null, "Import data berhasil", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
        Desktop desktop = null;
        if (Desktop.isDesktopSupported()) {
            desktop = Desktop.getDesktop();
        } else {
            JOptionPane.showMessageDialog(null, "Desktop tidak mendukung!", "WARNING", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_buttonBackupDataActionPerformed

    private void buttonRestoreDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRestoreDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRestoreDataActionPerformed

    private void resetForm() {
        cmbTahun.setSelectedIndex(0);
        cmbSubround.setSelectedIndex(0);
        cmdProvinsi.setSelectedIndex(0);
        cmbKako.setSelectedIndex(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBackupData;
    private javax.swing.JButton buttonRestoreData;
    private javax.swing.JComboBox cmbKako;
    private javax.swing.JComboBox cmbSubround;
    private javax.swing.JComboBox cmbTahun;
    private javax.swing.JComboBox cmdProvinsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
